#!/bin/bash

if [[ ! "$1" =~ ^[0-9]+$ ]]; then
    for file in $(find /var/www/ -type f -name "config.php" | xargs grep -rn '$slave_load_percent\s*=\s*[0-9]*;' | cut -d: -f1); do
        cat $file
    done
    exit
fi

if [[ ! "$1" =~ ^[0-9]+$ ]]; then
    echo "error option balance number"
    exit
fi



for file in $(find /var/www/ -type f -name "config.php" | xargs grep -rn '$slave_load_percent\s*=\s*[0-9]*;' | cut -d: -f1); do
    sed -i "s/\$slave_load_percent\s*=\s*\([0-9]*\);/\$slave_load_percent = $1;/" $file
done

for file in $(find /var/www/ -type f -name "config.php" | xargs grep -rn '$slave_load_percent\s*=\s*[0-9]*;' | cut -d: -f1); do
    cat $file
done

printf "\n\nnew balance value: $1\n"
exit
